server:
  port: 8086
  servlet:
    context-path: /charge-station
spring:
  application:
    name: charge-station-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8081/}
