
spring:
  datasource:
    url: ${CHARGE_STATION_DB:jdbc:postgresql://localhost:5433/charge}
    username: admin1
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        public-paths: /v1/users/user-token
        jwt:
          jwk-set-uri: http://localhost:8180/realms/dev/protocol/openid-connect/certs
  liquibase:
    change-log: classpath*:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
# Keycloak Ayarları
keycloak:
  auth-server-url: http://localhost:8180
  realm: dev
  resource: ev-csms
  ssl-required: none
  token-uri: http://localhost:8180/realms/dev/protocol/openid-connect/token
  users-uri: http://localhost:8180/admin/realms/dev/users
  client-secret: UomKzxrX1CVQ4ltCknsV9Gd5HWuzLNXK
  client-id: ev-csms
  admin-username: admin
  admin-password: 123456

springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  oAuthFlow:
    authorizationUrl: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
    tokenUrl: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
websocket:
  port: 8443
  host: localhost
